
spring:
  profiles:
    active: dev
  application:
      name: microservice-simple-provider-user

---
server:
  port: 8000
spring:
  profiles: dev

  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                           # 指定数据源
    platform: h2                        # 指定数据源类型
    schema: classpath:schema.sql        # 指定h2数据库的建表脚本
    data: classpath:data.sql            # 指定h2数据库的数据脚本
  output:
    ansi:
    enabled: false
  redis:
    # REDIS (RedisProperties)
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接池最大连接数（使用负值表示没有限制）
    max-active: 8
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    pool:
      max-wait: -1
    # 连接池中的最大空闲连接
      max-idle: 8
    # 连接池中的最小空闲连接
      min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 0

---
server:
  port: 8000
spring:
  profiles: test

---
server:
  port: 8000
spring:
  profiles: prod